name: Add new Complex N Rewarder

permissions:
  contents: write

on: [pull_request]

jobs:
  deployComplexNRewarder:
    if: startsWith(github.head_ref, 'complexrewarder/add/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - run: cp .env.example .env
      - run: yarn
      - name: Propose new complex rewarder
        env:
          SAFE_SIGNER_MNEMONIC: ${{ secrets.SAFE_SIGNER_MNEMONIC }}
          AURORA_API_KEY: ${{ secrets.AURORA_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: yarn hardhat run scripts/ops/safeDeployComplexNRewarder.ts --network aurora
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Added new Complex N Rewarder config to rewarderConfigs.json
