name: Set Pool Allocation

permissions:
  contents: write

on:
  pull_request:
    branches:
      - "allocation/set/**"

jobs:
  setAllocation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - run: cp .env.example .env
      - run: yarn
      - name: Propose pool allocation
        env:
          SAFE_PROPOSER_PRIVATE_KEY: ${{ secrets.SAFE_OPS_PROPOSER }}
          AURORA_API_KEY: ${{ secrets.AURORA_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: yarn hardhat run scripts/ops/proposerSetAllocation.ts --network aurora
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Removed allocationConfig.json due to transaction proposed on gnosis safe
