name: Set MCV1 Emissions

on: [workflow_dispatch]

jobs:
  setAllocation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Set required env variables
        run: cp .env.example .env
      - run: yarn
      - name: Propose updateTriPerBlock
        env:
          SAFE_PROPOSER_PRIVATE_KEY: ${{ secrets.SAFE_DAO_PROPOSER }}
          AURORA_API_KEY: ${{ secrets.AURORA_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: yarn hardhat run scripts/ops/proposerUpdateTriPerBlock.ts --network aurora
