name: Test Package

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          echo MNEMONIC="test test test test test test test test test test test junk" > .env
          echo INFURA_API_KEY="test" >> .env
          echo ETHERSCAN_API_KEY="test" >> .env
          echo AURORA_API_KEY="test" >> .env
      - run: |
          yarn
          yarn compile
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - run: |
          echo MNEMONIC="test test test test test test test test test test test junk" > .env
          echo INFURA_API_KEY="test" >> .env
          echo ETHERSCAN_API_KEY="test" >> .env
          echo AURORA_API_KEY="test" >> .env
      - run: |
          yarn
          yarn compile
      - run: yarn test
